<?php
/**
 * Created by PhpStorm.
 * User: lukaskammerling
 * Date: 11.07.18
 * Time: 18:31
 */

namespace Tests\tests;

use LKDev\HetznerCloud\Models\Datacenters\Datacenters;
use LKDev\HetznerCloud\Models\Locations\Locations;
use Tests\TestCase;

/**
 *
 */
class LocationsTest extends TestCase
{
    /**
     * @var \LKDev\HetznerCloud\Models\Locations\Locations
     */
    protected $locations;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->locations = new Locations();
    }

    /**
     *
     */
    public function testGet()
    {
        $location = $this->locations->get(12345);
        $this->assertEquals($location->id, 12345);
        $this->assertEquals($location->name, 'fsn1');
    }

    /**
     *
     */
    public function testAll()
    {
        $locations = $this->locations->all();

        $this->assertEquals(count($locations), 3);
        $this->assertEquals($locations[0]->id, 1);
        $this->assertEquals($locations[0]->name, 'fsn1');
        $this->assertEquals($locations[1]->id, 2);
        $this->assertEquals($locations[1]->name, 'nbg1');
        $this->assertEquals($locations[2]->id, 3);
        $this->assertEquals($locations[2]->name, 'hel1');
    }
}
