<?php
/**
 * Created by PhpStorm.
 * User: lukaskammerling
 * Date: 11.07.18
 * Time: 18:31
 */

namespace Tests\tests;

use LKDev\HetznerCloud\Models\Datacenters\Datacenters;
use LKDev\HetznerCloud\Models\Prices\Prices;
use Tests\TestCase;

/**
 *
 */
class PricingTest extends TestCase
{
    /**
     * @var \LKDev\HetznerCloud\Models\Prices\Prices
     */
    protected $prices;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->prices = new Prices();
    }

    /**
     * @skip
     */
    public function testAll()
    {
        $this->markTestSkipped(
            'Currently the prices api is not implemented on this sdk.'
        );
        $prices = $this->prices->all();

    }
}
