<?php
/**
 * Created by PhpStorm.
 * User: lukaskammerling
 * Date: 30.05.18
 * Time: 14:59
 */

namespace Tests\Endpoints\ServersEndpoint;

use LKDev\HetznerCloud\Models\Servers\Servers;
use Tests\TestCase;

/**
 *
 */
class ServersTest extends TestCase
{

    /**
     * @var Servers
     */
    protected $endpoint;

    /**
     *
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->endpoint = new Servers();
    }

    /**
     *
     */
    public function testAll()
    {
        $resp = json_encode($this->endpoint->all());

        $expected = $this->getExpectedResponse('servers/all');
        $this->assertEquals($expected, $resp);
    }

    /**
     *
     */
    /*public function testGet()
    {

    }*/

    /**
     *
     */
    /*public function testCreate()
    {

    }*/
}
